---
- hosts: all
  become: true
  pre_tasks:
    - name: install updates (Ubuntu)
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:
    - name: install apache2 and php packages for Ubuntu
      tags: apache, apache2, ubuntu
      apt:
        name:
          - apache2
          - libapache2-mod-php
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: copy default html file for site
      tags: apache, apache2
      copy:
        src: default_site.html
        dest: /var/www/html/index.html
        owner: vboxuser1
        group: root
        mode: 0644

- hosts: db_servers
  become: true
  tasks:
    - name: install mariadb package
      tags: db, mariadb, ubuntu
      apt: 
        name: mariadb-server
        state: latest
      when: ansible_distribution == "Ubuntu"
